---
- name: UWSGI
  hosts: all
  tasks:
    - name: install uwsgi
      become: yes
      pip:
        name: uwsgi
#    - name: start uwsgi
#      become: yes
#      command: uwsgi --ini /vagrant/wsgi.ini --daemonize /var/log/uwsgi
#    - name: copy uwsgi.conf
#      become: yes
#      copy:
#        src: /vagrant/uwsgi.conf
#        dest: /etc/init/uwsgi.conf
    - name: Creates directory
      become: yes      
      file: 
        path: /etc/uwsgi/vassals 
        state: directory
    - name: copy INI
      become: yes
      copy:
        src: ./project.ini
        dest: /etc/uwsgi/vassals/project.ini
    - name: copy Emperor.ini
      become: yes
      copy:
        src: ./emperor.ini
        dest: /etc/uwsgi/emperor.ini
    - name: copy Service
      become: yes
      copy:
        src: ./emperor.uwsgi.service
        dest: /etc/systemd/system/emperor.uwsgi.service
    - name: start Service
      become: yes
      command: systemctl start emperor.uwsgi.service
    - name: check Service
      become: yes
      shell: systemctl status emperor.uwsgi.service

