---
- name: Create {{project_name}} enviroment
  vars_files: 
   - variables.yml
  hosts: all
  tasks:
    - name: Install requiriments
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        name: python-pip,uwsgi,uwsgi-plugin-python,nginx,postgresql,libpq-dev,python-psycopg2,build-essential,libssl-dev,libffi-dev,python-dev
        state: latest
    - name: Install virtualenv
      become: yes
      become_method: sudo
      pip:
       name: virtualenv
       state: latest	 
    - name: Creates directory
      file: 
        path:  '{{venv_path}}'
        state: directory
    - name: create venv
      pip:
        name: mezzanine,fabric,psycopg2
        virtualenv: '{{venv_path}}'
    - name: Deploy {{project_name}}
      git: 
        repo: 'https://github.com/Ertinfagor/testapp.git'
        dest: '{{venv_path}}/{{ project_name }}/'
        force: yes

- name: UWSGI
  vars_files:
    - variables.yml
  hosts: all
  tasks:
    - name: Creates directory
      become: yes      
      file: 
        path: /etc/uwsgi/vassals 
        state: directory
    - name: copy INI
      become: yes
      template:
        src: ./configs/project.ini.j2
        dest: '/etc/uwsgi/vassals/{{ project_name }}.ini'
    - name: copy Emperor.ini
      become: yes
      copy:
        src: ./configs/emperor.ini
        dest: /etc/uwsgi/emperor.ini
    - name: copy Service
      become: yes
      copy:
        src: ./configs/emperor.uwsgi.service
        dest: /etc/systemd/system/emperor.uwsgi.service
    - name: start Service
      become: yes
      systemd:
       name: emperor.uwsgi
       state: restarted
       enabled: yes
       masked: no
 
 #     command: systemctl start emperor.uwsgi.service
- name: NGINX
  vars_files: 
  - variables.yml
  hosts: all
  tasks:
    - name: copy conf
      become: yes 
      template:
        src: ./configs/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
    - name: NGINX | Starting NGINX
      become: yes
      systemd:
        name: nginx
        state: restarted
        enabled: yes
        masked: no
- name: Postgres
  hosts: all
  become: yes
  become_user: postgres
  gather_facts: no
  vars_files:
   - variables.yml 
  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  
  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent


- name: migrate database
  vars_files:
  - variables.yml
  hosts: all
  tasks:
  - name: Copy settings
    template:
      src: ./configs/settings.py.j2
      dest: '{{venv_path}}/{{ project_name }}/{{ project_name }}/settings.py'
  - name: migrate db
    command: '{{venv_path}}/bin/python {{venv_path}}/{{ project_name }}/manage.py migrate'