---
- name: Create VENV
  hosts: all
  tasks:
    - name: Install python-pip
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        name: python-pip,build-essential,libssl-dev,libffi-dev,python-dev
        state: latest
    - name: Install virtualenv
      become: yes
      become_method: sudo
      pip:
       name: virtualenv
       state: latest	 
    - name: Creates directory
      file: path=~/venv state=directory
    - name: create venv
      pip:
        name: mezzanine,fabric,psycopg2
        virtualenv: ~/venv
#    - name: copy PROJECT
#      synchronize:
#        src: /vagrant/PROJECT/myproject
#        dest: /home/ubuntu/venv
    
    - name: Deploy project
      git: 
        repo: 'https://github.com/Ertinfagor/testapp.git'
        dest: /home/ubuntu/venv/myproject/
